name: push-myworkflow
on: push


jobs:
    push-job: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run my workflow
              run: |
                echo "Running my workflow..."
                # Add your workflow commands here